import katex from "katex";
import type { RsqDetail, ResultValue, SolveResponse } from "./types";
import { triggerDownload } from "./export";
import { fmtNum } from "./numbers";

// Build printable, self-contained reports from a solved RSQ. The HTML report
// typesets the formula as MathML (which renders in any modern browser without
// the KaTeX stylesheet), so a downloaded .html file is fully standalone.

function fmtValue(v: ResultValue["value"]): string {
  if (Array.isArray(v)) {
    const head = (v as unknown[]).slice(0, 6).map((x) => fmtNum(x as number));
    return `[${head.join(", ")}${v.length > 6 ? `, … ${v.length}` : ""}]`;
  }
  return fmtNum(v as number | string | boolean | null);
}

function splitRoles(result: SolveResponse) {
  const inputs: [string, ResultValue][] = [];
  const outputs: [string, ResultValue][] = [];
  for (const [k, rv] of Object.entries(result.results)) {
    (rv.role === "input" ? inputs : outputs).push([k, rv]);
  }
  return { inputs, outputs };
}

function mathml(latex: string): string {
  try {
    return katex.renderToString(latex, {
      output: "mathml",
      throwOnError: false,
      displayMode: true,
    });
  } catch {
    return `<code>${escapeHtml(latex)}</code>`;
  }
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

function rowsHtml(rows: [string, ResultValue][]): string {
  return rows
    .map(
      ([k, rv]) =>
        `<tr><td class="var">${escapeHtml(k)}</td>` +
        `<td class="num">${escapeHtml(fmtValue(rv.value))}</td>` +
        `<td class="unit">${escapeHtml(rv.unit || "")}</td></tr>`,
    )
    .join("");
}

/** A self-contained HTML report for one solved RSQ. */
export function buildReportHTML(detail: RsqDetail, result: SolveResponse): string {
  const { inputs, outputs } = splitRoles(result);
  const when = new Date().toLocaleString();
  const formula = detail.latex
    ? `<div class="formula">${mathml(detail.latex)}</div>`
    : `<pre class="signature">${escapeHtml(detail.signature)}</pre>`;

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>Anvil report: ${escapeHtml(detail.name)}</title>
<style>
  :root { color-scheme: light; }
  body { font: 15px/1.5 Georgia, "Iowan Old Style", "Palatino Linotype", serif;
         color: #1a1a1a; background: #fff; max-width: 46rem; margin: 3rem auto;
         padding: 0 1.5rem; }
  h1 { font-size: 1.6rem; margin: 0 0 .2rem; }
  .meta { color: #555; font-size: .85rem; margin-bottom: 1.4rem; }
  .meta code { font-family: "SF Mono", Menlo, Consolas, monospace; }
  .desc { font-size: 1rem; margin: 0 0 1.4rem; }
  .formula { margin: 1.2rem 0; font-size: 1.15rem; }
  .signature { font-family: "SF Mono", Menlo, Consolas, monospace;
               background: #f5f5f2; padding: .6rem .8rem; border-radius: 4px;
               overflow-x: auto; }
  h2 { font-size: 1.05rem; margin: 1.8rem 0 .5rem;
       font-variant: small-caps; letter-spacing: .04em; color: #333; }
  table { border-collapse: collapse; width: 100%; font-size: .95rem; }
  th, td { text-align: left; padding: .35rem .6rem;
           border-bottom: 1px solid #e6e6e0; }
  th { font-variant: small-caps; letter-spacing: .03em; color: #666;
       font-weight: 600; }
  td.var { font-family: "SF Mono", Menlo, Consolas, monospace; }
  td.num { text-align: right; font-variant-numeric: tabular-nums; }
  td.unit { color: #666; }
  footer { margin-top: 2.5rem; padding-top: 1rem; border-top: 1px solid #e6e6e0;
           color: #888; font-size: .8rem; }
</style>
</head>
<body>
  <h1>${escapeHtml(detail.name)}</h1>
  <div class="meta">
    ${detail.domain ? `${escapeHtml(detail.domain)} &middot; ` : ""}type ${escapeHtml(detail.type)}
    ${detail.version ? `&middot; v${escapeHtml(detail.version)}` : ""}
    &middot; solver: <code>${escapeHtml(result.method || "forward")}</code>
    &middot; ${escapeHtml(when)}
  </div>
  ${detail.description ? `<p class="desc">${escapeHtml(detail.description)}</p>` : ""}
  ${formula}
  ${inputs.length ? `<h2>Inputs</h2><table><thead><tr><th>variable</th><th class="num">value</th><th>unit</th></tr></thead><tbody>${rowsHtml(inputs)}</tbody></table>` : ""}
  ${outputs.length ? `<h2>Results</h2><table><thead><tr><th>variable</th><th class="num">value</th><th>unit</th></tr></thead><tbody>${rowsHtml(outputs)}</tbody></table>` : ""}
  <footer>Generated by Anvil Workbench.</footer>
</body>
</html>`;
}

/** A Markdown report for one solved RSQ. */
export function buildReportMarkdown(detail: RsqDetail, result: SolveResponse): string {
  const { inputs, outputs } = splitRoles(result);
  const when = new Date().toLocaleString();
  const lines: string[] = [];
  lines.push(`# ${detail.name}`, "");
  const meta = [
    detail.domain,
    `type ${detail.type}`,
    detail.version ? `v${detail.version}` : "",
    `solver: ${result.method || "forward"}`,
    when,
  ].filter(Boolean);
  lines.push(meta.join("  |  "), "");
  if (detail.description) lines.push(detail.description, "");
  if (detail.latex) lines.push("Formula:", "", "```latex", detail.latex, "```", "");
  else lines.push("```", detail.signature, "```", "");

  const table = (rows: [string, ResultValue][]) => {
    const out = ["| variable | value | unit |", "|----------|-------|------|"];
    for (const [k, rv] of rows) {
      out.push(`| \`${k}\` | ${fmtValue(rv.value)} | ${rv.unit || ""} |`);
    }
    return out;
  };
  if (inputs.length) lines.push("## Inputs", "", ...table(inputs), "");
  if (outputs.length) lines.push("## Results", "", ...table(outputs), "");
  lines.push("", "Generated by Anvil Workbench.");
  return lines.join("\n");
}

export function exportReportHTML(detail: RsqDetail, result: SolveResponse) {
  triggerDownload(
    `${detail.name}_report.html`,
    buildReportHTML(detail, result),
    "text/html",
  );
}

export function exportReportMarkdown(detail: RsqDetail, result: SolveResponse) {
  triggerDownload(
    `${detail.name}_report.md`,
    buildReportMarkdown(detail, result),
    "text/markdown",
  );
}
